import '@/app/globals.css';
import AppHeader from '@/components/application/AppHeader';
import FlowBar from '@/components/application/FlowBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ApplicationRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-screen bg-[url('/images/bg.jpeg')] bg-no-repeat bg-cover overflow-x-hidden max-w-7xl mx-auto px-10 pb-20">
        <AppHeader />
        {children}

        <div className="fixed bottom-20 right-16">
          <FlowBar />
        </div>
      </body>
    </html>
  );
}
