import {
  NextAuthProvider,
  SWRProvider,
  ToastProvider,
} from '@/components/providers';
import '@/app/globals.css';

export const metadata = {
  title: 'Halo',
  description: 'Generated by Leslie',
};

export default function MaintanenceRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.bootcdn.net/ajax/libs/bootstrap-icons/1.10.4/font/bootstrap-icons.min.css"
          rel="stylesheet"
        />
      </head>
      <body>
        <SWRProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </SWRProvider>

        <ToastProvider />
        <div id="overlay-root"></div>
      </body>
    </html>
  );
}
