import { NextAuthProvider, ToastProvider } from '@/components/providers';
import '@/app/globals.css';

export const metadata = {
  title: 'Halo',
  description: 'Generated by Leslie',
};

export default function MaintanenceRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />
      </head>
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
