import { NextAuthProvider } from '@/components/providers';
import '@/app/globals.css';

export const metadata = {
  title: 'Halo',
  description: 'Generated by Leslie',
};

export default function MaintanenceRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
