import '@/app/globals.css';
import ApplicationLayout from '@/components/ApplicationLayout';

export const metadata = {
  title: 'Leslie 的个人博客',
  description: 'Generated by Leslie with Next.js',
};

export default function ApplicationRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-deep-background overflow-x-hidden">
        <ApplicationLayout>{children}</ApplicationLayout>
      </body>
    </html>
  );
}
